title: "[Security] "
name: "Security ğŸ”"
description: "Security issue, hardening or audit request"
labels: ["area: security ğŸ”"]
body:
  - type: textarea
    id: security
    attributes:
      label: Describe the security concern or improvement
    validations:
      required: true
